# Generated by Django 4.0.5 on 2023-03-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_company_admin',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='role',
        ),
    ]
